### ISSUE TITLE
saveImage disturbing compilation

### ISSUE THREAD

**Issue by Lecale** [brentp/nim-plotly#64] opened 2020-09-15 18:47 UTC
I have a bit of code like this, which just doesn't work for me.
I've never used plotly, so perhaps I am missing something obvious

```
var jPlot = Plot[int](layout:jLayout)
var l1 = Trace[int](mode: PlotMode.Lines, `type`:PlotType.Scatter) 
l1.xs = this
l1.ys = that
l1.name = derek
jPlot.traces.add(l1)
jPlot.saveImage("Something.svg") #This upsets VisualStudioCode 
# Error: `saveImage` only supported if compiled with --threads:on!
# but if I add --threads it does not fix
```

**Comment by Vindaar** [comment] 2020-09-15 19:22
Hm, it's kind of weird that it also does not work with `threads:on`. Are you sure it is actually taking effect?

And what is the error you see after setting the flag?

**Comment by Lecale** [comment] 2020-09-16 11:01
This is what I can see. Through inexperience I may have done something very silly.
![image](https://user-images.githubusercontent.com/10641373/93328907-ad63e800-f81c-11ea-9b4e-b12124338222.png)

**Comment by Vindaar** [comment] 2020-09-16 11:14
Oh, this was a regression introduced by a change in the websocket library / how it uses the stdlib. I'm not entirely sure where the actual breakage came from. 

In any case, this was fixed in #60.

So the problem happens, because you are still using the latest tagged release of plotly.
```sh
nimble install "plotly@#head"
``` 
should update you to the latest release for the time being.

@brentp: Would you mind pushing a version `v0.2.1` and tagging it?

**Comment by Lecale** [comment] 2020-09-16 11:32
Awesome + 5

**Comment by brentp** [comment] 2020-09-16 13:32
> @brentp: Would you mind pushing a version `v0.2.1` and tagging it?

done. thanks!

**Comment by brentp** [comment] 2020-09-16 13:42
@Vindaar any ideas on this: https://travis-ci.com/github/brentp/nim-plotly/jobs/385734545 ?

**Comment by Vindaar** [comment] 2020-09-16 14:08
Seems to be a regression due to a change in `radToDeg`. Will open a PR with a fix.

**Comment by Vindaar** [comment] 2020-09-21 08:57
I just noticed that the mentioned PR has been merged. Using the most current devel version the tests compile and pass on my machine again. 

I just restarted the builds for the on the master branch (was surprised to find out I can indeed do that from travis-ci.com!). Will close this issue, if they succeed.

**Comment by Vindaar** [comment] 2020-10-13 08:02
Closing this issue, as CI is finally passing again on devel.

**Closed by Vindaar** 2020-10-13 08:02 UTC
